### ISSUE TITLE
Función de parada o tiempo de espera

### ISSUE THREAD

**Issue by paulamartinezperez** [IntelligentRoboticsLabs/gb_dialog#6]
Buenas tardes @jginesclavero ,
Usando el repositorio de gb_dialog, hemos encontrado un problema. Al tener lanzado un nodo durante cierto tiempo haciendo listen(),  cuando pasa un tiempo se queda bloqueado y deja de escuchar.

**Comment by jginesclavero** [comment]
Hola @paulamartinezperez,
Es normal, piensa que cuando llamas a la función listen() estás abriendo un stream de datos contra un servidor en la nube de DialogFlow. No puedes estar eternamente enviándole datos, por eso el propio servidor cierra la conexión después de cierto tiempo y te dará una respuesta. Si solo ha escuchado ruido o no ha escuchado nada la respuesta que recibirás será vacía o de que no ha podido determinar la intención de lo que ha escuchado. En ese momento tendrás que volver a llamar a la función listen().
Si no es eso lo que está pasando, comentame que te sucede, si hay algún mensaje de error, etc, para poder ayudarte.
